services:
  certgen:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: elastic-certgen
    volumes:
      - ./instances.yml:/usr/share/elasticsearch/instances.yml
      - ./certs:/usr/share/elasticsearch/certs
    entrypoint: >
      bash -c "rm -rf /usr/share/elasticsearch/certs/* &&
               mkdir -p /usr/share/elasticsearch/certs &&
               bin/elasticsearch-certutil ca --silent --pem -out /usr/share/elasticsearch/certs/ca.zip &&
               unzip -q /usr/share/elasticsearch/certs/ca.zip -d /usr/share/elasticsearch/certs &&
               bin/elasticsearch-certutil cert --silent --pem --in /usr/share/elasticsearch/instances.yml --out /usr/share/elasticsearch/certs/certs.zip --ca-cert /usr/share/elasticsearch/certs/ca/ca.crt --ca-key /usr/share/elasticsearch/certs/ca/ca.key &&
               unzip -q /usr/share/elasticsearch/certs/certs.zip -d /usr/share/elasticsearch/certs &&
               echo '✅ Done generating certs in ./certs' &&
               sleep 10"