services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:9.0.0
    container_name: filebeat
    user: "0"
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro
      - ./certs:/usr/share/filebeat/certs:ro
    networks:
      - elknet
networks:
  elknet:
    external: true