services:
  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    container_name: logstash
    ports: ["5044:5044", "9600:9600"]
    restart: always
    networks: ["elknet"]
    environment:
      log.level: "warn"
      http.host: "0.0.0.0"
      monitoring.enabled: true
      monitoring.elasticsearch.hosts: [ "https://elasticsearch:9200" ]
      monitoring.elasticsearch.username: "elastic"
      monitoring.elasticsearch.password: ${ELASTIC_PASSWORD}
      monitoring.elasticsearch.ssl.certificate_authority: "/usr/share/logstash/config/certs/ca/ca.crt"
    volumes:
       - ./certs:/usr/share/logstash/config/certs      
       - ./pipeline/:/usr/share/logstash/pipeline/
       - ./jdbc-drivers:/usr/share/logstash/jdbc-drivers
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5
networks:
  elknet:
    external: true